### PR TITLE
Translate api.template.ss into English

### PR DESCRIPTION
**Pull request by yernende**
There is a try to translate one of the documentation pages into English. If the translation turns to be fine, I will maybe work on this further.
Some fragments are hard for me to understand, so I just leaved them untouched.

Hope that was helpful, Yernende.

### CODE REVIEW

**Comment by kobezzza** [comment]
@yernende thanks for your help! I'll merge this PR soon.

**Comment by trikadin** [comment]
Big thanks, @yernende. We'll check your translation as soon as possible and will merge this PR.

**Comment by kobezzza** [comment]
@yernende I think that the "template" more preferred "pattern", and so, like, everything is good.

**Comment by kobezzza** [comment]
@yernende thanks!

**Pull request merged**
